-- AlterTable
ALTER TABLE "member_permissions" ADD COLUMN     "can_add_members" BOOLEAN DEFAULT false,
ADD COLUMN     "can_approve_activities" BOOLEAN DEFAULT false,
ADD COLUMN     "can_assign_passwords" BOOLEAN DEFAULT false,
ADD COLUMN     "can_create_activities" BOOLEAN DEFAULT false,
ADD COLUMN     "can_edit_members" BOOLEAN DEFAULT false,
ADD COLUMN     "can_export_data" BOOLEAN DEFAULT false,
ADD COLUMN     "can_manage_all_messages" BOOLEAN DEFAULT false,
ADD COLUMN     "can_manage_card_numbers" BOOLEAN DEFAULT false,
ADD COLUMN     "can_manage_financials" BOOLEAN DEFAULT false,
ADD COLUMN     "can_manage_membership" BOOLEAN DEFAULT false,
ADD COLUMN     "can_send_group_messages" BOOLEAN DEFAULT false,
ADD COLUMN     "can_view_activities" BOOLEAN DEFAULT false,
ADD COLUMN     "can_view_financials" BOOLEAN DEFAULT false,
ADD COLUMN     "can_view_members" BOOLEAN DEFAULT false,
ADD COLUMN     "can_view_statistics" BOOLEAN DEFAULT false,
ADD COLUMN     "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;
